Add sample for Vk_ext_inline_uniform_block
google/vulkan_test_applications pull request #226
Opened 2022-03-31 16:06 UTC by RenfengLiu

2022-04-04 13:19 UTC, AWoloszyn approved these changes

2022-04-04 13:20 UTC, AWoloszyn requested changes
Would you be able to fix the typo. Other that that looks good.

2022-04-06 16:00 UTC, krmoule requested changes

2022-04-06 19:21 UTC, RenfengLiu commented on vulkan_helpers/helper_functions.cpp
>        /* pNext = */ nullptr,
Thanks for helping the review. This is a good catch, I think it must be when I did force push from my deskkit and somehow this part get missed.

2022-04-06 19:29 UTC, merged