Remove legacy application options.
google/vulkan_test_applications pull request #241
Opened 2022-08-15 16:17 UTC by AWoloszyn

The old API was bloated and bad. We have switched to a new
API. This updates all remaining samples to the new API
and removes the old one completely.

2022-08-15 17:29 UTC, krmoule requested changes

2022-08-15 17:29 UTC, krmoule commented on application_sandbox/timeline_semaphore_cross_queue/main.cpp
> +          .SetDeviceExtensions(&timeline_semaphore_features),
I think this needs the EnableAsyncComputeQueue() called.

2022-08-15 17:29 UTC, krmoule commented on application_sandbox/overlapping_frames/main.cpp
>    const uint32_t default_size = 1024 * 1024;
I think this default_size can be removed.

2022-08-15 18:49 UTC, RenfengLiu approved these changes

2022-08-16 13:35 UTC, krmoule approved these changes

2022-08-16 13:39 UTC, merged